export const ROUTES = {
  HOME:        '/',
  MISSION:     '/mission',
  FOUNDER:     '/founder',
  CONSTITUTION:'/constitution.pdf',
  ABOUT:       '/about',
  PROJECTS:    '/projects',
  PROJECTS_HEALTHCARE: '/projects/healthcare',
  PROJECTS_EDUCATION: '/projects/education',
  PROJECTS_FOOD_SERVICES: '/projects/food-services',
  HEALTHCARE:  '/healthcare',
  EDUCATION:   '/education',
  COMMUNITY:   '/community',
  GALLERY:     '/gallery',
  NEWS:        '/news',
  DONATE:      '/donate',
  CONTACT:     '/contact',
  LOGIN:       '/login',
  ADMIN: {
    ROOT:         '/admin',
    PROJECTS:     '/admin/projects',
    HOSPITALS:    '/admin/hospitals',
    NEWS:         '/admin/news',
    EVENTS:       '/admin/events',
    GALLERY:      '/admin/gallery',
    DONATIONS:    '/admin/donations',
    VOLUNTEERS:   '/admin/volunteers',
    APPOINTMENTS: '/admin/appointments',
    CONTACTS:     '/admin/contacts',
    SETTINGS:     '/admin/settings',
  },
} as const;

